node {
  properties(
    [
      pipelineTriggers([cron('@hourly')])
    ]
  )
  def commit_id
  stage('preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"                        
    commit_id = readFile('.git/commit-id').trim()
  }
  dir('city-data-gathering') {
    stage('test') {
      def testContainer = docker.image('node:latest')
      testContainer.pull()
      testContainer.inside {
        sh 'npm install'
        sh 'npm test'
      }
    }
    stage('docker build/push') {
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
        def app = docker.build("zepaiva/city-data-gathering:${commit_id}", '.').push()
      }
    }
  }
}